package com.bs.teachassistant.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bs.teachassistant.entity.Course;
import com.bs.teachassistant.entity.Less;
import com.bs.teachassistant.entity.Note;
import com.bs.teachassistant.entity.Score;
import com.bs.teachassistant.entity.User;

import com.bs.teachassistant.database.CourseDao;
import com.bs.teachassistant.database.LessDao;
import com.bs.teachassistant.database.NoteDao;
import com.bs.teachassistant.database.ScoreDao;
import com.bs.teachassistant.database.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDaoConfig;
    private final DaoConfig lessDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig scoreDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CourseDao courseDao;
    private final LessDao lessDao;
    private final NoteDao noteDao;
    private final ScoreDao scoreDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        lessDaoConfig = daoConfigMap.get(LessDao.class).clone();
        lessDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        scoreDaoConfig = daoConfigMap.get(ScoreDao.class).clone();
        scoreDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        courseDao = new CourseDao(courseDaoConfig, this);
        lessDao = new LessDao(lessDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        scoreDao = new ScoreDao(scoreDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Course.class, courseDao);
        registerDao(Less.class, lessDao);
        registerDao(Note.class, noteDao);
        registerDao(Score.class, scoreDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        courseDaoConfig.clearIdentityScope();
        lessDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        scoreDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public LessDao getLessDao() {
        return lessDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ScoreDao getScoreDao() {
        return scoreDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
